name: Lint and Type Check

on:
  pull_request:
    branches: 
      - main
      - dev 
      - prod

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry virtualenvs
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Run black (check only)
        run: poetry run black --check .

      - name: Run isort (check only)
        run: poetry run isort --check-only .

      - name: Run flake8
        run: poetry run flake8 --max-line-length=100 --ignore=E203,W503 .

      - name: Run mypy
        run: poetry run mypy . --exclude '^.*\b(migrations)\b.*$'

      - name: Run pylint (Django optimized)
        env:
          DJANGO_SETTINGS_MODULE: my_tennis_club.settings
        run: poetry run pylint --load-plugins pylint_django --ignore=manage.py --disable=all --exclude='^.*\b(migrations)\b.*$' $(git ls-files '*.py')

